apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao
  namespace: default
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "socle"
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: socle-secrets-external
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: socle-secrets
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: kubernetes
        property: DISCORD_TOKEN
    - secretKey: GUILD_ID
      remoteRef:
        key: kubernetes
        property: GUILD_ID
    - secretKey: CLIENT_ID
      remoteRef:
        key: kubernetes
        property: CLIENT_ID
    - secretKey: WELCOME_CHANNEL_ID
      remoteRef:
        key: kubernetes
        property: WELCOME_CHANNEL_ID
    - secretKey: MEMBER_ROLE_ID
      remoteRef:
        key: kubernetes
        property: MEMBER_ROLE_ID
    - secretKey: ADMIN_ROLE_ID
      remoteRef:
        key: kubernetes
        property: ADMIN_ROLE_ID
